name: open-forest

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  test:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: apt-get update
        run: sudo apt-get update
      - name: Install dependencies
        run: >
          sudo apt-get install -y 
          cmake 
          libglew-dev 
          libboost-all-dev
          libmpg123-dev 
          libzzip-dev 
          libfreeimage-dev 
          libfreetype-dev 
          xorg-dev 
          libglu1-mesa-dev 
          libopenal-dev
          libogg-dev
          libsndfile-dev
          libphysfs-dev
          libaldmb1-dev
          libplib-dev
          libopus-dev
      - name: Show libraries
        run: |
          sudo apt list
      - name: Init submodules
          git submodule init
          git submodule update
      - name: Build
        run: |
          ./build.sh
      - name: Debug
        run: |
          ls .
          ls build
      
